## Importing PyTorch

> **Note:** Before running any of the code in this notebook, you should have gone through the [PyTorch setup steps](https://pytorch.org/get-started/locally/). 

> However, **if you're running on Google Colab**, everything should work (Google Colab comes with PyTorch and other libraries installed).

Let's start by importing PyTorch and checking the version we're using.

In [1]:
import torch

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8772, 0.4304, 0.9207],
        [0.8362, 0.1063, 0.4509],
        [0.2291, 0.5480, 0.6610],
        [0.0417, 0.4806, 0.7225],
        [0.7419, 0.3800, 0.3220]])


In [3]:
# Check for GPU
torch.cuda.is_available()

True

In [4]:
#Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[8.5250e-01, 1.5646e-04, 2.2155e-01, 6.3365e-01],
        [3.3817e-02, 6.2818e-01, 5.7722e-01, 8.2293e-01],
        [1.4168e-01, 1.6142e-01, 2.7364e-01, 2.1628e-01]])

In [5]:
random_tensor.ndim

2

Alright, it outputs `torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

In [6]:
#Create a random tensor with the similar shape of an immage
random_img_tensor = torch.rand(size = (224,224,3))#h,w,color channels
random_img_tensor.shape , random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
# Zeros and ones Tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
ones.dtype,random_tensor.dtype

(torch.float32, torch.float32)

In [10]:
# creating a range of tensors and tensor-like
torch.range(0,10)

C:\Users\Naman Gupta\AppData\Local\Temp\ipykernel_9668\566311653.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
torch.__version__

'2.3.1'

In [12]:
one_to_end = torch.arange(start = 1,end = 1000 , step = 77)
one_to_end

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [13]:
#creating tensor-like
ten_zeros = torch.zeros_like(input = one_to_end)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#TENSOR DATA-TYPES
float_32 = torch.tensor([3.0,6.0,9.0],
                       dtype = None,
                       device = None,
                       requires_grad = False)
float_32,float_32.dtype

(tensor([3., 6., 9.]), torch.float32)

In [15]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
float_16 * float_32

tensor([ 9., 36., 81.])

In [17]:
int32 = torch.tensor([3,6,9],
                    dtype = torch.int32
                    )

In [18]:
float_16 * int32

tensor([ 9., 36., 81.], dtype=torch.float16)

In [19]:
#for data type = tensor.dtype
#for shape - tensor.shape
#for device - tensor.device


In [20]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5665, 0.4196, 0.4361, 0.9940],
        [0.7457, 0.8948, 0.5372, 0.0148],
        [0.8814, 0.5458, 0.4686, 0.1476]])

In [21]:
print(some_tensor)
print(f'DataType of Tensor :{some_tensor.dtype}')
print(f'Shape of Tensor : {some_tensor.shape}')
print(f'Device Tensor is on : {some_tensor.device}')

tensor([[0.5665, 0.4196, 0.4361, 0.9940],
        [0.7457, 0.8948, 0.5372, 0.0148],
        [0.8814, 0.5458, 0.4686, 0.1476]])
DataType of Tensor :torch.float32
Shape of Tensor : torch.Size([3, 4])
Device Tensor is on : cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [22]:
#Few operation on tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [23]:
tensor * 10

tensor([10, 20, 30])

In [24]:
tensor - 10

tensor([-9, -8, -7])

In [25]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [26]:
#In-Build functions in PyTorch
torch.mul(tensor,10)

tensor([10, 20, 30])

In [27]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [28]:
#Matrix Multiplication
#1. Element-wise Multiplication
#2. Matrix multipplication

### Matrix multiplication 

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.



The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our `tensor` variable with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [29]:
#1 Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [30]:
#2 Matrix Multiplication (Dot Product)
torch.matmul(tensor,tensor) #1*1 + 2*2 + 3*3

tensor(14)

In [31]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [32]:
%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: total: 0 ns
Wall time: 1.01 ms


In [33]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)  

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
tensor_B , tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [38]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [39]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [40]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [41]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min , max , mean ,  sum , etc (tensor Aggregation)

In [47]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
#Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [49]:
#Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [55]:
#Find the mean (torch.mean() function requires float32 dtype)
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
#Find the Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [57]:
#Finding the positional min and max
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# Find the position in tensor that has the minimum value with argmin() -> return index 
x.argmin()

tensor(0)

In [60]:
# Find the position in tensor that has the maximum value with argmax() -> return index 
x.argmax()

tensor(9)

### Reshaping ,  stacking , Squeezing , Unsequeezing
1. Reshaping -> reshape an input tensor to a defined shape
2. View -> Return of an input tensor of a shape but keeps the same memory as the original tensor
3. Stacking -> combine multiple tensor on the top of each other(vstack) or side by side(hstack)
4. Squeeze -> remove all '1' dimensions from a tensor
5. Unsqueeze -> add '1' dimension to a target tensor
6. Permute -> return a view of an input with dimensions permuted in a certain way

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors. 

Let's try them out.

First, we'll create a tensor.

In [73]:
# Add an extra dimension
x_reshape = x.reshape(1,10)
x_reshape , x_reshape.shape

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [74]:
# Add an extra dimension
x_reshape = x.reshape(10,1)
x_reshape , x_reshape.shape

(tensor([[ 5],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]))

In [75]:
# Change the view
z = x.view(1,10)
z , z.shape

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [76]:
# changing z changes x becuase a view of a tensor shares the same memory as the original
z[: , 0] = 5
z , x

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [77]:
#Stack tensors on top of each other
x_stacked = torch.stack([x , x, x, x], dim = 0)
x_stacked

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [78]:
# torch.squeeze() - remove all simple dimensions from a target tensor
x_reshape

tensor([[ 5],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [79]:
x_reshape.shape

torch.Size([10, 1])

In [80]:
x_reshape.squeeze()

tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [82]:
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# Remove extra dimension from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])
Previous shape: torch.Size([10, 1])

New tensor: tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])
New shape: torch.Size([10])


In [83]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
New shape: torch.Size([1, 10])


In [85]:
# Create tensor with specific shape
x_original = torch.rand(size=(256, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([256, 224, 3])
New shape: torch.Size([3, 256, 224])


In [99]:
torch.manual_seed(0)
tensor1 = torch.rand(7,7)
tensor1 , tensor1.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 torch.Size([7, 7]))

In [100]:
tensor2 = torch.rand(1,7)
tensor2 , tensor2.shape

(tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 torch.Size([1, 7]))

In [101]:
torch.matmul(tensor1 , tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [102]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [103]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [104]:
x[0][0]

tensor([1, 2, 3])

In [109]:
x[0][2][2]

tensor(9)

In [110]:
x[: , 0]

tensor([[1, 2, 3]])

In [111]:
x[: , : ,1]

tensor([[2, 5, 8]])

In [112]:
x[:,1 ,1]

tensor([5])

In [113]:
x[0,0,:]

tensor([1, 2, 3])

In [114]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [119]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)#By defualt it is float64
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [120]:
array.dtype , tensor.dtype

(dtype('float64'), torch.float32)

In [121]:
array = array +1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [122]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [123]:
tensor.dtype , numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [124]:
tensor  = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short: 

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right? 

In [133]:
torch.rand(2,3)

tensor([[0.1100, 0.2121, 0.9704],
        [0.8369, 0.2820, 0.3742]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

In [159]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1830, 0.4459, 0.5643, 0.9260],
        [0.2614, 0.8203, 0.4365, 0.2625],
        [0.0646, 0.0412, 0.9883, 0.3753]])

Tensor B:
tensor([[0.5250, 0.6356, 0.8399, 0.9267],
        [0.9055, 0.1296, 0.4199, 0.2041],
        [0.2143, 0.6186, 0.9693, 0.0994]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [164]:
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [165]:
!nvidia-smi

Thu Jul 25 03:38:27 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.85                 Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P3             14W /   35W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [166]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [167]:
torch.cuda.device_count()

1

In [168]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')